# Generated by Django 2.1.11 on 2019-08-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('style', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('height', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='foot',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.Table'),
        ),
        migrations.RunSQL(sql="insert into furniture_table (id, name, height) values (1, 'test1', 11)", reverse_sql=""),
        migrations.RunSQL(sql="insert into furniture_foot (number, style, table_id) values (1, 'plain', 1)", reverse_sql=""),
        migrations.RunSQL(sql="insert into furniture_foot (number, style, table_id) values (2, 'plain', 1)", reverse_sql=""),
        migrations.RunSQL(sql="insert into furniture_table (id, name, height) values (2, 'test2', 22)", reverse_sql=""),
        migrations.RunSQL(sql="insert into furniture_foot (number, style, table_id) values (1, 'square', 2)",
                          reverse_sql=""),
        migrations.RunSQL(sql="insert into furniture_foot (number, style, table_id) values (2, 'round', 2)",
                          reverse_sql=""),
    ]
